/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RpBadgeVariant } from "./components/rp-badge/rp-badge";
import { RpRemoveMealDetail } from "./components/rp-day-slot/rp-day-slot";
import { RpCardClickDetail, RpFavoriteToggleDetail } from "./components/rp-recipe-card/rp-recipe-card";
import { RpSearchChangeDetail } from "./components/rp-search-bar/rp-search-bar";
export { RpBadgeVariant } from "./components/rp-badge/rp-badge";
export { RpRemoveMealDetail } from "./components/rp-day-slot/rp-day-slot";
export { RpCardClickDetail, RpFavoriteToggleDetail } from "./components/rp-recipe-card/rp-recipe-card";
export { RpSearchChangeDetail } from "./components/rp-search-bar/rp-search-bar";
export namespace Components {
    /**
     * A small pill/chip used for tags, categories, cuisines and status labels.
     * Use the default slot to prefix the label with an icon.
     */
    interface RpBadge {
        /**
          * Text shown inside the badge.
         */
        "label": string;
        /**
          * Visual style variant.
          * @default 'default'
         */
        "variant": RpBadgeVariant;
    }
    /**
     * Represents one day of the weekly meal planner. Shows the assigned recipe
     * (if any) or an empty state. When empty, place an "Assign recipe" control
     * in the default slot; it is only rendered while the slot is empty of a meal.
     */
    interface RpDaySlot {
        /**
          * Day label, e.g. "Monday".
         */
        "day": string;
        /**
          * Image of the recipe assigned to this day, if any.
         */
        "recipeImage"?: string;
        /**
          * Title of the recipe assigned to this day, if any.
         */
        "recipeTitle"?: string;
    }
    /**
     * A generic empty-state placeholder (no favorites yet, no search results, etc.).
     * Place a call-to-action button/link in the default slot.
     */
    interface RpEmptyState {
        /**
          * Heading text.
         */
        "heading": string;
        /**
          * Emoji or short glyph shown above the heading.
          * @default '🍽️'
         */
        "icon": string;
        /**
          * Supporting message.
         */
        "message"?: string;
    }
    /**
     * A card that displays a recipe summary (image, title, category/area, favorite toggle).
     * Consumers render extra actions (e.g. an "Add to plan" button) via the default slot.
     */
    interface RpRecipeCard {
        /**
          * Recipe area/cuisine, e.g. "Italian".
         */
        "area"?: string;
        /**
          * Recipe category, e.g. "Dessert".
         */
        "category"?: string;
        /**
          * Whether the whole card body is clickable (navigates to details).
          * @default true
         */
        "clickable": boolean;
        /**
          * Whether the recipe is currently favorited.
          * @default false
         */
        "favorite": boolean;
        /**
          * Recipe thumbnail image URL.
         */
        "image"?: string;
        /**
          * Unique id of the recipe, echoed back in emitted events.
         */
        "recipeId": string;
        /**
          * Recipe title.
         */
        "recipeTitle": string;
    }
    /**
     * A debounced search input. Emits `rpSearchChange` as the user types (debounced)
     * and `rpSearchSubmit` immediately on Enter/form submit.
     * Use the `icon` slot to override the default search icon.
     */
    interface RpSearchBar {
        /**
          * Debounce delay in ms before rpSearchChange fires.
          * @default 300
         */
        "debounce": number;
        /**
          * Placeholder text.
          * @default 'Search recipes...'
         */
        "placeholder": string;
        /**
          * Current value of the input (controlled from the outside).
          * @default ''
         */
        "value": string;
    }
}
export interface RpDaySlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpDaySlotElement;
}
export interface RpRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpRecipeCardElement;
}
export interface RpSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRpSearchBarElement;
}
declare global {
    /**
     * A small pill/chip used for tags, categories, cuisines and status labels.
     * Use the default slot to prefix the label with an icon.
     */
    interface HTMLRpBadgeElement extends Components.RpBadge, HTMLStencilElement {
    }
    var HTMLRpBadgeElement: {
        prototype: HTMLRpBadgeElement;
        new (): HTMLRpBadgeElement;
    };
    interface HTMLRpDaySlotElementEventMap {
        "rpRemoveMeal": RpRemoveMealDetail;
    }
    /**
     * Represents one day of the weekly meal planner. Shows the assigned recipe
     * (if any) or an empty state. When empty, place an "Assign recipe" control
     * in the default slot; it is only rendered while the slot is empty of a meal.
     */
    interface HTMLRpDaySlotElement extends Components.RpDaySlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpDaySlotElementEventMap>(type: K, listener: (this: HTMLRpDaySlotElement, ev: RpDaySlotCustomEvent<HTMLRpDaySlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpDaySlotElementEventMap>(type: K, listener: (this: HTMLRpDaySlotElement, ev: RpDaySlotCustomEvent<HTMLRpDaySlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpDaySlotElement: {
        prototype: HTMLRpDaySlotElement;
        new (): HTMLRpDaySlotElement;
    };
    /**
     * A generic empty-state placeholder (no favorites yet, no search results, etc.).
     * Place a call-to-action button/link in the default slot.
     */
    interface HTMLRpEmptyStateElement extends Components.RpEmptyState, HTMLStencilElement {
    }
    var HTMLRpEmptyStateElement: {
        prototype: HTMLRpEmptyStateElement;
        new (): HTMLRpEmptyStateElement;
    };
    interface HTMLRpRecipeCardElementEventMap {
        "rpCardClick": RpCardClickDetail;
        "rpFavoriteToggle": RpFavoriteToggleDetail;
    }
    /**
     * A card that displays a recipe summary (image, title, category/area, favorite toggle).
     * Consumers render extra actions (e.g. an "Add to plan" button) via the default slot.
     */
    interface HTMLRpRecipeCardElement extends Components.RpRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpRecipeCardElementEventMap>(type: K, listener: (this: HTMLRpRecipeCardElement, ev: RpRecipeCardCustomEvent<HTMLRpRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpRecipeCardElementEventMap>(type: K, listener: (this: HTMLRpRecipeCardElement, ev: RpRecipeCardCustomEvent<HTMLRpRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpRecipeCardElement: {
        prototype: HTMLRpRecipeCardElement;
        new (): HTMLRpRecipeCardElement;
    };
    interface HTMLRpSearchBarElementEventMap {
        "rpSearchChange": RpSearchChangeDetail;
        "rpSearchSubmit": RpSearchChangeDetail;
    }
    /**
     * A debounced search input. Emits `rpSearchChange` as the user types (debounced)
     * and `rpSearchSubmit` immediately on Enter/form submit.
     * Use the `icon` slot to override the default search icon.
     */
    interface HTMLRpSearchBarElement extends Components.RpSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRpSearchBarElementEventMap>(type: K, listener: (this: HTMLRpSearchBarElement, ev: RpSearchBarCustomEvent<HTMLRpSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRpSearchBarElementEventMap>(type: K, listener: (this: HTMLRpSearchBarElement, ev: RpSearchBarCustomEvent<HTMLRpSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRpSearchBarElement: {
        prototype: HTMLRpSearchBarElement;
        new (): HTMLRpSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "rp-badge": HTMLRpBadgeElement;
        "rp-day-slot": HTMLRpDaySlotElement;
        "rp-empty-state": HTMLRpEmptyStateElement;
        "rp-recipe-card": HTMLRpRecipeCardElement;
        "rp-search-bar": HTMLRpSearchBarElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * A small pill/chip used for tags, categories, cuisines and status labels.
     * Use the default slot to prefix the label with an icon.
     */
    interface RpBadge {
        /**
          * Text shown inside the badge.
         */
        "label": string;
        /**
          * Visual style variant.
          * @default 'default'
         */
        "variant"?: RpBadgeVariant;
    }
    /**
     * Represents one day of the weekly meal planner. Shows the assigned recipe
     * (if any) or an empty state. When empty, place an "Assign recipe" control
     * in the default slot; it is only rendered while the slot is empty of a meal.
     */
    interface RpDaySlot {
        /**
          * Day label, e.g. "Monday".
         */
        "day": string;
        /**
          * Fired when the user removes the assigned meal.
         */
        "onRpRemoveMeal"?: (event: RpDaySlotCustomEvent<RpRemoveMealDetail>) => void;
        /**
          * Image of the recipe assigned to this day, if any.
         */
        "recipeImage"?: string;
        /**
          * Title of the recipe assigned to this day, if any.
         */
        "recipeTitle"?: string;
    }
    /**
     * A generic empty-state placeholder (no favorites yet, no search results, etc.).
     * Place a call-to-action button/link in the default slot.
     */
    interface RpEmptyState {
        /**
          * Heading text.
         */
        "heading": string;
        /**
          * Emoji or short glyph shown above the heading.
          * @default '🍽️'
         */
        "icon"?: string;
        /**
          * Supporting message.
         */
        "message"?: string;
    }
    /**
     * A card that displays a recipe summary (image, title, category/area, favorite toggle).
     * Consumers render extra actions (e.g. an "Add to plan" button) via the default slot.
     */
    interface RpRecipeCard {
        /**
          * Recipe area/cuisine, e.g. "Italian".
         */
        "area"?: string;
        /**
          * Recipe category, e.g. "Dessert".
         */
        "category"?: string;
        /**
          * Whether the whole card body is clickable (navigates to details).
          * @default true
         */
        "clickable"?: boolean;
        /**
          * Whether the recipe is currently favorited.
          * @default false
         */
        "favorite"?: boolean;
        /**
          * Recipe thumbnail image URL.
         */
        "image"?: string;
        /**
          * Fired when the card body is clicked.
         */
        "onRpCardClick"?: (event: RpRecipeCardCustomEvent<RpCardClickDetail>) => void;
        /**
          * Fired when the favorite (heart) button is toggled.
         */
        "onRpFavoriteToggle"?: (event: RpRecipeCardCustomEvent<RpFavoriteToggleDetail>) => void;
        /**
          * Unique id of the recipe, echoed back in emitted events.
         */
        "recipeId": string;
        /**
          * Recipe title.
         */
        "recipeTitle": string;
    }
    /**
     * A debounced search input. Emits `rpSearchChange` as the user types (debounced)
     * and `rpSearchSubmit` immediately on Enter/form submit.
     * Use the `icon` slot to override the default search icon.
     */
    interface RpSearchBar {
        /**
          * Debounce delay in ms before rpSearchChange fires.
          * @default 300
         */
        "debounce"?: number;
        /**
          * Fired (debounced) whenever the input value changes.
         */
        "onRpSearchChange"?: (event: RpSearchBarCustomEvent<RpSearchChangeDetail>) => void;
        /**
          * Fired immediately when the user presses Enter or submits.
         */
        "onRpSearchSubmit"?: (event: RpSearchBarCustomEvent<RpSearchChangeDetail>) => void;
        /**
          * Placeholder text.
          * @default 'Search recipes...'
         */
        "placeholder"?: string;
        /**
          * Current value of the input (controlled from the outside).
          * @default ''
         */
        "value"?: string;
    }

    interface RpBadgeAttributes {
        "label": string;
        "variant": RpBadgeVariant;
    }
    interface RpDaySlotAttributes {
        "day": string;
        "recipeTitle": string;
        "recipeImage": string;
    }
    interface RpEmptyStateAttributes {
        "heading": string;
        "message": string;
        "icon": string;
    }
    interface RpRecipeCardAttributes {
        "recipeId": string;
        "recipeTitle": string;
        "image": string;
        "category": string;
        "area": string;
        "favorite": boolean;
        "clickable": boolean;
    }
    interface RpSearchBarAttributes {
        "value": string;
        "placeholder": string;
        "debounce": number;
    }

    interface IntrinsicElements {
        "rp-badge": Omit<RpBadge, keyof RpBadgeAttributes> & { [K in keyof RpBadge & keyof RpBadgeAttributes]?: RpBadge[K] } & { [K in keyof RpBadge & keyof RpBadgeAttributes as `attr:${K}`]?: RpBadgeAttributes[K] } & { [K in keyof RpBadge & keyof RpBadgeAttributes as `prop:${K}`]?: RpBadge[K] } & OneOf<"label", RpBadge["label"], RpBadgeAttributes["label"]>;
        "rp-day-slot": Omit<RpDaySlot, keyof RpDaySlotAttributes> & { [K in keyof RpDaySlot & keyof RpDaySlotAttributes]?: RpDaySlot[K] } & { [K in keyof RpDaySlot & keyof RpDaySlotAttributes as `attr:${K}`]?: RpDaySlotAttributes[K] } & { [K in keyof RpDaySlot & keyof RpDaySlotAttributes as `prop:${K}`]?: RpDaySlot[K] } & OneOf<"day", RpDaySlot["day"], RpDaySlotAttributes["day"]>;
        "rp-empty-state": Omit<RpEmptyState, keyof RpEmptyStateAttributes> & { [K in keyof RpEmptyState & keyof RpEmptyStateAttributes]?: RpEmptyState[K] } & { [K in keyof RpEmptyState & keyof RpEmptyStateAttributes as `attr:${K}`]?: RpEmptyStateAttributes[K] } & { [K in keyof RpEmptyState & keyof RpEmptyStateAttributes as `prop:${K}`]?: RpEmptyState[K] } & OneOf<"heading", RpEmptyState["heading"], RpEmptyStateAttributes["heading"]>;
        "rp-recipe-card": Omit<RpRecipeCard, keyof RpRecipeCardAttributes> & { [K in keyof RpRecipeCard & keyof RpRecipeCardAttributes]?: RpRecipeCard[K] } & { [K in keyof RpRecipeCard & keyof RpRecipeCardAttributes as `attr:${K}`]?: RpRecipeCardAttributes[K] } & { [K in keyof RpRecipeCard & keyof RpRecipeCardAttributes as `prop:${K}`]?: RpRecipeCard[K] } & OneOf<"recipeId", RpRecipeCard["recipeId"], RpRecipeCardAttributes["recipeId"]> & OneOf<"recipeTitle", RpRecipeCard["recipeTitle"], RpRecipeCardAttributes["recipeTitle"]>;
        "rp-search-bar": Omit<RpSearchBar, keyof RpSearchBarAttributes> & { [K in keyof RpSearchBar & keyof RpSearchBarAttributes]?: RpSearchBar[K] } & { [K in keyof RpSearchBar & keyof RpSearchBarAttributes as `attr:${K}`]?: RpSearchBarAttributes[K] } & { [K in keyof RpSearchBar & keyof RpSearchBarAttributes as `prop:${K}`]?: RpSearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A small pill/chip used for tags, categories, cuisines and status labels.
             * Use the default slot to prefix the label with an icon.
             */
            "rp-badge": LocalJSX.IntrinsicElements["rp-badge"] & JSXBase.HTMLAttributes<HTMLRpBadgeElement>;
            /**
             * Represents one day of the weekly meal planner. Shows the assigned recipe
             * (if any) or an empty state. When empty, place an "Assign recipe" control
             * in the default slot; it is only rendered while the slot is empty of a meal.
             */
            "rp-day-slot": LocalJSX.IntrinsicElements["rp-day-slot"] & JSXBase.HTMLAttributes<HTMLRpDaySlotElement>;
            /**
             * A generic empty-state placeholder (no favorites yet, no search results, etc.).
             * Place a call-to-action button/link in the default slot.
             */
            "rp-empty-state": LocalJSX.IntrinsicElements["rp-empty-state"] & JSXBase.HTMLAttributes<HTMLRpEmptyStateElement>;
            /**
             * A card that displays a recipe summary (image, title, category/area, favorite toggle).
             * Consumers render extra actions (e.g. an "Add to plan" button) via the default slot.
             */
            "rp-recipe-card": LocalJSX.IntrinsicElements["rp-recipe-card"] & JSXBase.HTMLAttributes<HTMLRpRecipeCardElement>;
            /**
             * A debounced search input. Emits `rpSearchChange` as the user types (debounced)
             * and `rpSearchSubmit` immediately on Enter/form submit.
             * Use the `icon` slot to override the default search icon.
             */
            "rp-search-bar": LocalJSX.IntrinsicElements["rp-search-bar"] & JSXBase.HTMLAttributes<HTMLRpSearchBarElement>;
        }
    }
}
